# Generated by Django 4.2 on 2024-03-08 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_student_user_is_teacher_alter_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_teacher',
            new_name='is_doctor',
        ),
    ]
