# Generated by Django 4.2 on 2024-04-06 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_attendance_subject_alter_attendance_student_session_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='session',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
    ]
