# Generated by Django 4.2 on 2024-04-06 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_attendance_session_delete_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='subject',
        ),
        migrations.AddField(
            model_name='doctor',
            name='subject',
            field=models.ManyToManyField(related_name='doctor_subject', to='core.subject'),
        ),
    ]
