# Generated by Django 4.2 on 2024-06-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_timetable_department_timetable_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='timeTableImage',
            field=models.ImageField(blank=True, null=True, upload_to='doctorTimeTable/'),
        ),
    ]
